### ISSUE TITLE
Max32 Hello-World: cannot access the sources

### ISSUE THREAD

**Issue by slpp95prashanth** [sergev/qemu#13]
Hi @sergev,

Thank you for the work.

I am trying to create a bare metal firmware for PIC32, So can I ask for the sources of Max32 Hello world (bootloader, application, linker script). And also trying to build through xc32-gcc so linker script will also be helpful.

Regards
Prashanth S

**Comment by slpp95prashanth** [comment]
Thank You

**Comment by sergev** [comment]
Hi Prashanth,

Sorry, your message got lost in my overflowing mailbox. Here you can find sources of a simple bare metal application for pic32mx7. Here I use a modern Clang compiler for the build.

https://github.com/sergev/vak-opensource/tree/master/microcontrollers/pic32-max32

Regards,
--Serge
